name: release

on:
  release:
    types: [published]

jobs:
  build-windows:
    defaults:
      run:
        working-directory: .\\build
    strategy:
      fail-fast: false
      matrix:
        name:
          - windows_x86_64
          # - windows_arm64
          # - windows_x86
    runs-on: windows-2022
    outputs:
      output-artifact-id: ${{ steps.artifact-upload-step.output.artifact-id }}
    steps:
    - uses: actions/checkout@v4
    - name: Determine Release Tag
      env:
        RELEASE: ${{ github.ref_name }}
      id: release_tag
      run: |
        $tag = $Env:RELEASE.split(".")[0]
        echo "tag=$tag" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
        echo "3P_WEBRTC_BUILD_RELEASE_VERSION=$Env:RELEASE" | Out-File -FilePath .\\VERSION -Encoding utf8 -Append
    - name: Disk Cleanup
      run: |
        Get-PSDrive
        # Cache 済み Docker Image の削除
        # Clean unused docker images
        docker rmi $(docker images -q -a)
        # Android SDK の削除
        # Delete Android SDK
        Remove-Item -Recurse -Force $Env:ANDROID_HOME -ErrorAction Ignore
        Remove-Item -Recurse -Force $Env:ANDROID_NDK_HOME -ErrorAction Ignore
        # JVM の削除
        # Delete JVM
        Remove-Item -Recurse -Force $Env:JAVA_HOME_11_X64 -ErrorAction Ignore
        Remove-Item -Recurse -Force $Env:JAVA_HOME_8_X64 -ErrorAction Ignore
        Get-PSDrive
    - run: "& .\\build.${{ matrix.name }}.ps1 \"${{ steps.release_tag.outputs.tag }}_release\""
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      id: artifact-upload-step
      with:
        name: webrtc.${{ matrix.name }}.tar.bz2
        path: build\_package\${{ matrix.name }}\webrtc.tar.bz2
  build-macos:
    defaults:
      run:
        working-directory: ./build
    strategy:
      fail-fast: false
      matrix:
        name:
          # - macos_arm64
          - macos_x86_64
          # - ios
    runs-on: macos-11
    outputs:
      output-artifact-id: ${{ steps.artifact-upload-step.output.artifact-id }}
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode 13.0
      run: sudo xcode-select --switch /Applications/Xcode_13.0.app/Contents/Developer
    - run: brew install ninja
    - name: Determine Release Tag
      env:
        RELEASE: ${{ github.ref_name }}
      id: release_tag
      run: |
        echo "tag=${RELEASE%%.*}" >> "$GITHUB_OUTPUT"
        echo "3P_WEBRTC_BUILD_RELEASE_VERSION=${RELEASE}" >> "VERSION"
    - run: ./build.${{ matrix.name }}.sh "${{ steps.release_tag.outputs.tag }}_release"    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      id: artifact-upload-step
      with:
        name: webrtc.${{ matrix.name }}.tar.bz2
        path: build/_package/${{ matrix.name }}/webrtc.tar.bz2
  build-linux:
    if: false  
    defaults:
      run:
        working-directory: ./build
    strategy:
      fail-fast: false
      matrix:
        name:
          # - raspberry-pi-os_armv6
          # - raspberry-pi-os_armv7
          # - raspberry-pi-os_armv8
          # - ubuntu-18.04_armv8
          # - ubuntu-20.04_armv8
          # - ubuntu-18.04_x86_64
          # - ubuntu-20.04_x86_64
          # - ubuntu-22.04_x86_64
          - android
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
    - uses: actions/checkout@v4
    - name: Disk Cleanup
      run: |
        df -h
        docker container prune -f
        docker image prune -a -f
        # 3.9GB
        sudo rm -rf /usr/local/share/boost
        # 17GB
        sudo rm -rf /usr/share/dotnet
        df -h
    - name: Determine Release Tag
      env:
        RELEASE: ${{ github.ref_name }}
      id: release_tag
      run: |
        echo "tag=${RELEASE%%.*}" >> "$GITHUB_OUTPUT"
        echo "3P_WEBRTC_BUILD_RELEASE_VERSION=${RELEASE}" >> "VERSION"
    - run: ./build.${{ matrix.name }}.sh "${{ steps.release_tag.outputs.tag }}_release"
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: webrtc.${{ matrix.name }}.tar.bz2
        path: build/_package/${{ matrix.name }}/webrtc.tar.bz2
  package-macos:
    needs:
    - build-macos
    strategy:
      matrix:
        os: [macos-11]
        addrsize: ['64']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Determine Release Tag
      env:
        RELEASE: ${{ github.ref_name }}
      id: release_tag
      run: |
        echo "tag=${RELEASE%%.*}" >> "$GITHUB_OUTPUT"
        echo "RELEASE=${RELEASE}" >> "$GITHUB_OUTPUT"
    - uses: secondlife/action-autobuild@v3.8.0
      with:
        addrsize: ${{ matrix.addrsize }}
        token: ${{ github.token }}
        build-args: ${{ needs.build-macos.outputs.output-artifact-id }}
  package-windows:
    needs:
    - build-windows 
    strategy:
      matrix:
        os: [windows-2022]
        addrsize: ['64']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Determine Release Tag
      env:
        RELEASE: ${{ github.ref_name }}
      id: release_tag
      run: |
        echo "tag=${RELEASE%%.*}" >> "$GITHUB_OUTPUT"
        echo "RELEASE=${RELEASE}" >> "$GITHUB_OUTPUT"
    - uses: secondlife/action-autobuild@v3.8.0
      with:
        addrsize: ${{ matrix.addrsize }}
        token: ${{ github.token }}
        build-args: ${{ needs.build-macos.outputs.output-artifact-id }}
  release:
    needs:
    - package-windows
    - package-macos
    runs-on: [ubuntu-latest]
    if: startsWith(github.ref, 'refs/tags/m')
    steps:
      - uses: secondlife/action-autobuild-release@v3
        with:
          public: false