name: test

on:
  workflow_dispatch:
      github_run_id:
        description: 'Run id from which to create package'
        default: '8303274173'
        required: true
jobs:
  package-windows:
    needs:
    - build-windows 
    strategy:
      matrix:
        os: [windows-2022]
        addrsize: ['64']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Determine Release Tag
      env:
        RELEASE: ${{ github.ref_name }}
      id: release_tag
      run: |
        echo "tag=${RELEASE%%.*}" >> "$GITHUB_OUTPUT"
        echo "RELEASE=${RELEASE}" >> "$GITHUB_OUTPUT"
    - uses: secondlife/action-autobuild@v3.8.0
      with:
        addrsize: ${{ matrix.addrsize }}
        token: ${{ github.token }}
  release:
    needs:
    - package-windows
    - package-macos
    runs-on: [ubuntu-latest]
    if: startsWith(github.ref, 'refs/tags/m')
    steps:
      - uses: secondlife/action-autobuild-release@v3
        with:
          public: false